# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91849c28477e86d8ffaf6390ecafbac5991ff83e8d9a71b33ee90315c40a6254c8dcb3695de2683cc08dbc232a75bfe255619d26ddde6e7658970cde099b49cf

test:
  secret_key_base: 1a958afb8414b7860c863fc2382bdd4b9c63655a03b737f23c19a12627a30d70909cb07eff5eb284f929c775be707ce5678c8851b6b93a5101529701f1f2f530

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
